### ISSUE TITLE
BROKEN apps

### ISSUE THREAD

**Issue by M3dvidek** [Fausto-Korpsvart/Tokyonight-GTK-Theme#67]
Hi,
I love your themes but in every one I had the same issue with bad color consistence in libadwaita apps.
Thanks for resolving.
![Screenshot from 2024-10-14 19-24-57](https://github.com/user-attachments/assets/9c41cf8d-f083-4426-a4d0-ec56dc6688f7)
![Screenshot from 2024-10-14 19-24-41](https://github.com/user-attachments/assets/aac26c4f-83da-4a89-adbf-af2e746b1fe3)
![Screenshot from 2024-10-14 19-24-28](https://github.com/user-attachments/assets/e5734077-5706-4e21-b817-edd14314db3d)

**Comment by Fausto-Korpsvart** [comment]
> Hi, I love your themes but in every one I had the same issue with bad color consistence in libadwaita apps. Thanks for resolving.

Thank you for reporting and for using the themes.

Regarding the problem you are experiencing, I would like to know what distro you are using?,
what version of GNOME do you have installed?

Since in Gnome 46, so far it's working fine, but if you're using Gnome 47, I haven't done deep testing yet, but in the few tests I've done I haven't seen that problem anywhere in any libadwaita app.

Here is a test in Gnome 47.
![tn-gnome-47](https://github.com/user-attachments/assets/4d327320-db50-4dd6-bc04-1fdd92e1b62b)

**Comment by M3dvidek** [comment]
Hi

**Comment by M3dvidek** [comment]
Hi,
I closed it accidentally but thanks for responding I am using gnome 46.4 on debian testing. I tried

**Comment by M3dvidek** [comment]
Hi, 
Thanks for looking on my problem I am using debian testing with gnome 46.4 I think and I installed it with the install.sh with the -libadwaita.

**Comment by Fausto-Korpsvart** [comment]
> Hi, Thanks for looking on my problem I am using debian testing with gnome 46.4 I think and I installed it with the install.sh with the -libadwaita.

Yes, you should read the README, it explains which folders should be moved to which directories for the theme to work properly, with the installer the file copy for `libadwaita` is done automatically with the `-l` parameter.
Good thing it's working now.

**Comment by M3dvidek** [comment]
Sorry I struggle with the GitHub gui I did not wanted to close it it's just that I want to reply but it closes on default. It's not working but maybe it is because some parts are gnome 47, some apps in testing are migrated but some are not so it doesn't show as fully updated I will look at it today.

**Comment by Fausto-Korpsvart** [comment]
> Sorry I struggle with the GitHub gui I did not wanted to close it it's just that I want to reply but it closes on default. It's not working but maybe it is because some parts are gnome 47, some apps in testing are migrated but some are not so it doesn't show as fully updated I will look at it today.

That's what I'm saying, I've tested the theme as it is in the repository in the last current version with Gnome 46 and in the last ones with Gnome 47 and everything is working fine, I've already tried to replicate the problem and I don't understand why this problem is happening.
The screenshots I put above are from Gnome 47 and, as you can see, there is no problem, I will do more tests and fix it when I find the problem.

**Comment by M3dvidek** [comment]
I will try to reinstall the theme and maybe it will work.

**Comment by Fausto-Korpsvart** [comment]
The theme has been updated, I hope the problem has been fixed.

**Comment by M3dvidek** [comment]
Thanks I tried it with the nightfox and it worked beautifully
